version: "3.7"

services:
  analyser:
    build: ./analyser
    image: protoinct/analyser
    volumes:
      - ./analyser:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./analyser/.env
    depends_on:
      - broker

  broker:
    image: nats-streaming:0.21.2-alpine3.13

  collector_db:
    image: mongo:4.2-bionic
    restart: always
    env_file:
      - ./collector/.env
    ports:
      - 27017:27017

  collector:
    build: ./collector
    image: protoinct/collector
    volumes:
      - ./collector:/usr/src/app
    ports:
      - 3000:3000
    env_file:
      - ./collector/.env
    depends_on:
      - broker
      - collector_db
